        
       PROGRAM PRESSAO_REDUZIDA_AO_NIVEL_DO_MAR

C DECLARAÇÃO DAS VARIÁVEIS DOS DOIS ARQUIVOS  
       CHARACTER*24 CIDADE(8)
       CHARACTER*10 DATAS(8)
         INTEGER    HORA(8)     
            REAL    LAT(8), LON(8), ALT(8), TMAX(8), TMIN(8), URMAX(8),
     *              URMIN(8), TDMAX(8), TDMIN(8), PRESSMAX(8),
     *              PRESSMIN(8), VEL(8), DIR(8), RAJ(8), RAD(8),
     *              PREC(8), PVTDMAX(8), PVTDMIN(8),RMMAX(8), RMMIN(8),
     *              TVMAX(8),TVMIN(8),PRESSRED_PMAX(8),TVKMAX(8),
     *              TVKMIN(8),PRESSRED_PMIN(8),ELEVMAX(8),ELEVMIN(8)

C DECLARANDO CONSTANTES
             RD = 287.05307
              G = 9.8
      
C ABRINDO OS ARQUIVOS DE LEITURA E ESCRITA
       OPEN(1,FILE='estacoes.txt',STATUS='OLD')                 
       OPEN(2,FILE='dados_estacoes.txt',STATUS='OLD')
       OPEN(3,FILE='pressao_reduzida.txt',STATUS='OLD')

C LOOP DO CÓDIGO
       DO 100 I=1,8

C LER O ARQUIVO COM LATITUDE, LONGITUDE E ALTITUDE DAS ESTAÇÕES
           READ(1,10)LAT(I),LON(I),ALT(I),CIDADE(I)
10         FORMAT(F10.6,1X,F10.6,1X,F7.2,1X,A24)
C           PRINT*, LAT(I),LON(I),ALT(I),CIDADE(I)

C LER O ARQUIVO COM AS VARIAVEIS METEOROLOGICAS
           READ(2,20)DATAS(I),HORA(I),TMAX(I),TMIN(I),URMAX(I),
     *          URMIN(I),TDMAX(I),TDMIN(I),PRESSMAX(I),PRESSMIN(I),
     *          VEL(I),DIR(I),RAJ(I),RAD(I),PREC(I)
20         FORMAT(A10,1X,I4,1X,F4.1,1X,F4.1,1X,F5.1,1X,F5.1,
     *           1X,F4.1,1X,F4.1,1X,F6.1,1X,F6.1,1X,F3.1,1X,F5.1,1X,
     *           F3.1,1X,F7.2,1X,F3.1)
C           PRINT*, DATAS(I),HORA(I),TMAX(I),TMIN(I),URMAX(I),
C     *          URMIN(I),TDMAX(I),TDMIN(I),PRESSMAX(I),PRESSMIN(I),
C     *          VEL(I),DIR(I),RAJ(I),RAD(I),PREC(I)

C CALCULANDO A PRESSAO DE VAPOR COM TDMAX

         PVTDMAX(I) = 6.11*10**((A*TDMAX(I))/(B+TDMAX(I)))

         IF(TDMAX(I).GT.0)THEN
           A=7.5
           B=237.3
         ELSE
           IF(TDMAX(I).LE.0)THEN
             A = 9.5
             B = 265.5 
           ENDIF 
         ENDIF
C         PRINT*, 'PVTDMAX',PVTDMAX(I)

C CALCULANDO A PRESSAO DE VAPOR COM TDMIN

         PVTDMIN(I) = 6.11*10**((A*TDMIN(I))/(B+TDMIN(I)))

         IF(TDMIN(I).GT.0)THEN
           A=7.5
           B=237.3
         ELSE
           IF(TDMIN(I).LE.0)THEN
             A = 9.5
             B = 265.5 
           ENDIF 
         ENDIF
C         PRINT*, 'PVTDMIN',PVTDMIN(I)          
        
C CALCULANDO A RAZAO DE MISTURA COM PVTDMAX E PRESSMAX
        RMMAX(I) = 0.622*(PVTDMAX(I)/(PRESSMAX(I) - PVTDMAX(I)))
C        PRINT*, 'RAZAO DE MISTURA MAXIMA', RMMAX(I)

C CALCULANDO A RAZAO DE MISTURA COM PVTDMIN E PRESSMIN
        RMMIN(I) = 0.622*(PVTDMIN(I)/(PRESSMIN(I) - PVTDMIN(I)))
C        PRINT*, 'RAZAO DE MISTURA MINIMA', RMMIN(I)

C CALCULANDO A TEMPERATURA VIRTUAL COM TMAX
        TVMAX(I) = TMAX(I)*(1 + RMMAX(I)*0.6)
C        PRINT*, 'TEMPERATURA VIRTUAL MAX', TVMAX(I)

C CALCULANDO A TEMPERATURA VIRTUAL COM TMIN
        TVMIN(I) = TMIN(I)*(1 + RMMIN(I)*0.6)
C         PRINT*,'TEMPERATURA VIRTUAL MIN',TVMIN(I)

C CONVERTENDO A TEMPERATURA VIRTUAL MAXIMA DE CELSIUS PARA KELVIN
        TVKMAX(I) = TVMAX(I) + 273.15
C        PRINT*, 'TEMPERATURA VIRTUAL MAX EM K', TVKMAX(I)

C CONVERTENDO A TEMPERATURA VIRTUAL MINIMA DE CELSIUS PARA KELVIN
        TVKMIN(I) = TVMIN(I) + 273.15
C        PRINT*, 'TEMPERATURA VIRTUAL MIN EM K', TVKMIN(I)

C CALCULANDO A PRESSAO REDUZIDA AO NIVEL DO MAR USANDO PRESSMAX E TVKMAX
         ELEVMAX(I) = EXP((ALT(I)*G)/(TVKMAX(I)*RD))  
C         PRINT*, ELEV(I)
        PRESSRED_PMAX(I) = PRESSMAX(I)*(ELEVMAX(I))
        PRINT*,'PRESSAO REDUZIDA MAX', PRESSRED_PMAX(I)

C CALCULANDO A PRESSAO REDUZIDA AO NIVEL DO MAR USANDO PRESSMIN E TVKMIN
         ELEVMIN(I) = EXP((ALT(I)*G)/(TVKMIN(I)*RD))
C         PRINT*, ELEV(I)
        PRESSRED_PMIN(I) = PRESSMIN(I)*(ELEVMIN(I))
        PRINT*,'PRESSAO REDUZIDA MIN', PRESSRED_PMIN(I)

C GRAVANDO INFORMAÇOES METEOROLOGICAS EM ARQUIVO DE SAIDA
        WRITE(3,30)DATAS(I),HORA(I),TMAX(I),TMIN(I),URMAX(I),
     *          URMIN(I),TDMAX(I),TDMIN(I),PRESSRED_PMAX(I),
     *          PRESSRED_PMIN(I),VEL(I),DIR(I),RAJ(I),RAD(I),
     *          PREC(I)
30      FORMAT(A10,1X,I4,1X,F4.1,1X,F4.1,1X,F5.1,1X,F5.1,
     *         1X,F4.1,1X,F4.1,1X,F7.2,1X,F7.2,1X,F3.1,
     *         1X,F5.1,1X,F3.1,1X,F7.2,1X,F3.1)

100    CONTINUE  
       END  

C####################################################################
C           COMPILAR: gfortran pressao_reduzida.f
C              RODAR: ./a.out
C####################################################################
